### ISSUE TITLE
Have To Clear Cache After Creating New Redirect

### ISSUE THREAD

**Issue by eat-sleep-code** [iamandycohen/UrlRewrite#16]
I am running Sitecore 8.0, Update 4.

After creating a new Simple Redirect it does not work -- until I manually go in and clear the cache via sitecore/admin/cache.aspx

After clearing the cache it works fine.

Shouldn't this be handled automatically by the module?

**Comment by eat-sleep-code** [comment]
Actually on my staging server this does not appear to work at all!   I have cleared the cache, tried restarting IIS, tried restarting the server, even tried reinstalling the module.

My redirect was created in the folder created by the module (Sample Redirects) and is called test.   It is a Simple Redirect that points to 'http://www.google.com'

**Comment by eat-sleep-code** [comment]
I note this error in the UrlRewrite logs:
`
3864 14:56:32 INFO  UrlRewrite[production.master]::Refreshing Simple Redirect [/sitecore/content/URL Management/Test] after save event
3864 14:56:32 ERROR UrlRewrite[production.master]::Exception occured when saving item after save - Item ID: {66508B17-8440-4071-810E-6F46AEA46272} Item Path: /sitecore/content/URL Management/Test
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: innerField
Source: Sitecore.Kernel
   at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
   at Sitecore.Data.Fields.CustomField..ctor(Field innerField)
   at Hi.UrlRewrite.Templates.BaseEnabledItem.get_Enabled() in c:\projects\UrlRewrite\Hi.UrlRewrite\Templates\BaseEnabledItem.cs:line 42
   at Hi.UrlRewrite.Processing.RulesEngine.CreateInboundRuleFromSimpleRedirectItem(SimpleRedirectItem simpleRedirectItem, RedirectFolderItem redirectFolderItem) in c:\projects\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 167
   at Hi.UrlRewrite.Processing.RulesEngine.GetInboundRules() in c:\projects\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 73
   at Hi.UrlRewrite.Processing.RulesEngine.UpdateRulesCache(Item item, Item redirectFolderItem, Action`3 action) in c:\projects\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 298
   at Hi.UrlRewrite.Processing.RulesEngine.RefreshRule(Item item, Item redirectFolderItem) in c:\projects\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 281
   at Hi.UrlRewrite.Processing.UrlRewriteItemEventHandler.RunItemSaved(Item item, ItemChanges itemChanges) in c:\projects\UrlRewrite\Hi.UrlRewrite\Processing\UrlRewriteItemEventHandler.cs:line 82
`

**Comment by iamandycohen** [comment]
Did you make sure to publish the entire site?  It should include templates that need to be published.  They are located at /Sitecore/templates/User Defined/UrlRewrite.

**Comment by iamandycohen** [comment]
Also, clearing the cache manually is not necessary.  This is handled entirely in the item saved and item saved remote events.

**Comment by iamandycohen** [comment]
This has been fixed with the latest release.

https://github.com/iamandycohen/UrlRewrite/commit/e89a4bcf77551e11a007ebc9235aa98e081e15b9
