### ISSUE TITLE
Error in log every time I hit a redirect

### ISSUE THREAD

**Issue by kmac23va** [iamandycohen/UrlRewrite#19]
This is in a clean instance of Sitecore 8.1 U1 with URL Rewrite 1.8 installed. I copied the sample set into my home directory, then set the website dropdown to my website. I then tried to hit "external1" from the simple redirect, but every time, I get the error below. Locally, it's also like everything just stopped working, so I'm trying to figure out why this might be. Thanks.

7204 21:00:20 ERROR UrlRewrite[web]::Exception occured
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Hi.UrlRewrite
   at Hi.UrlRewrite.Processing.RewriteHelper.ReplaceBackReferences(Match match, String input, String backReferenceVariable) in c:\git\UrlRewrite\Hi.UrlRewrite\Processing\RewriteHelper.cs:line 30
   at Hi.UrlRewrite.Processing.RewriteHelper.ReplaceConditionBackReferences(Match conditionMatch, String input) in c:\git\UrlRewrite\Hi.UrlRewrite\Processing\RewriteHelper.cs:line 19
   at Hi.UrlRewrite.Processing.InboundRewriter.ProcessRedirectAction(InboundRule inboundRule, Uri uri, Match inboundRuleMatch, Match lastConditionMatch, InboundRuleResult ruleResult) in c:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriter.cs:line 417
   at Hi.UrlRewrite.Processing.InboundRewriter.ProcessRegularExpressionInboundRule(Uri originalUri, InboundRule inboundRule) in c:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriter.cs:line 270
   at Hi.UrlRewrite.Processing.InboundRewriter.ProcessInboundRule(Uri originalUri, InboundRule inboundRule) in c:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriter.cs:line 204
   at Hi.UrlRewrite.Processing.InboundRewriter.ProcessRequestUrl(Uri requestUri, List`1 inboundRules) in c:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriter.cs:line 59
   at Hi.UrlRewrite.Processing.InboundRewriteProcessor.ProcessUri(Uri requestUri, Database db, InboundRewriter urlRewriter) in c:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriteProcessor.cs:line 76
   at Hi.UrlRewrite.Processing.InboundRewriteProcessor.Process(HttpRequestArgs args) in c:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriteProcessor.cs:line 36

**Comment by kmac23va** [comment]
Looks like it was because I hadn't published everything to web, actually. I'm going to reinstall my local Sitecore to see if that solves things on that side. Thanks.
