### ISSUE TITLE
Issue while building the reporting database

### ISSUE THREAD

**Issue by bhasyamvinod** [iamandycohen/UrlRewrite#20]
We are getting the following error on Sitecore 8.1 update -2 after installing the module, any help is highly appreciated. 
Exception: System.TypeLoadException
Message: Derived method 'Filter' in type 'Hi.UrlRewrite.Analytics.ByUrlRewriteRedirect' from assembly 'Hi.UrlRewrite, Version=1.8.5779.17263, Culture=neutral, PublicKeyToken=null' cannot reduce access.
Source: mscorlib
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Sitecore.Reflection.ReflectionUtil.CreateObject(String assembly, String className, Object[] parameters)
   at Sitecore.Reflection.ReflectionUtil.CreateObject(String typeName, Object[] parameters)
   at Sitecore.ExperienceAnalytics.Core.Repositories.DimensionDefinitionService.CreateDimensionFromConfig(XmlElement childNode)
   at Sitecore.ExperienceAnalytics.Core.Repositories.DimensionDefinitionService.LoadDimensionsFromConfig(String pathToConfigNode)
   at Sitecore.ExperienceAnalytics.Core.Repositories.DimensionDefinitionService..ctor(String pathToConfigNode, ILogger logger)

**Comment by iamandycohen** [comment]
There is a pull request for this issue that I have not had time to
integrate.  My apologies.

**Comment by bhasyamvinod** [comment]
Hi,
Can you please point me to the exact pull request please?

Thanks,
Vinod.

**Comment by iamandycohen** [comment]
https://github.com/iamandycohen/UrlRewrite/pull/18

**Comment by bhasyamvinod** [comment]
Hi Andy,

I wanted to cleanup the Url rewrite module on my Sitecore instance, is
there any easy way of doing it?

Can you please provide any cleanup script you may have.

Thanks,
Vinod

**Comment by iamandycohen** [comment]
By cleanup do you mean remove?

**Comment by bhasyamvinod** [comment]
Yes Andy, it would be really helpful

**Comment by iamandycohen** [comment]
Can I ask why?

**Comment by bhasyamvinod** [comment]
Client decided to implement rewrites on reverse proxy and wants to remove
the module

**Comment by iamandycohen** [comment]
If you decompress the package file you can see everything that is installed.

**Comment by ddysart** [comment]
I'd echo the original issue is still occuring on v8.1u3. It's breaking all of the reporting processing so no anayltics make it into the reporting db (including WFFM form submissions).

I did clone the update from Slev and it solved the issue.

**Comment by iamandycohen** [comment]
Yes sorry .  Still have not had time.

**Comment by ddysart** [comment]
heh, been there. Back testing on older versions is a pain.

**Comment by iamandycohen** [comment]
This is fixed in https://github.com/iamandycohen/UrlRewrite/releases/tag/v1.8.1.3
