### ISSUE TITLE
Unable to initialize the module

### ISSUE THREAD

**Issue by gaurav2ks** [iamandycohen/UrlRewrite#22]
After installing the component following exceptions are getting logged.

7812 06:45:12 INFO  Initializing URL Rewrite.
7812 06:45:39 INFO  UrlRewrite[core]::Adding 0 rules to Cache [core]
7812 06:46:08 ERROR UrlRewrite::Exception during initialization.
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: innerField
Source: Sitecore.Kernel
   at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
   at Sitecore.Data.Fields.CustomField..ctor(Field innerField)
   at Hi.UrlRewrite.Templates.Folders.RedirectFolderItem.get_SiteNameRestriction() in C:\git\UrlRewrite\Hi.UrlRewrite\Templates\Folders\RedirectFolderItem.cs:line 51
   at Hi.UrlRewrite.Processing.RulesEngine.GetSiteNameRestriction(RedirectFolderItem redirectFolder) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 221
   at Hi.UrlRewrite.Processing.RulesEngine.CreateInboundRuleFromSimpleRedirectItem(SimpleRedirectItem simpleRedirectItem, RedirectFolderItem redirectFolderItem) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 165
   at Hi.UrlRewrite.Processing.RulesEngine.GetInboundRules() in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 82
   at Hi.UrlRewrite.Processing.RulesEngine.GetCachedInboundRules() in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 254
   at Hi.UrlRewrite.Processing.InboundRuleInitializer.Process(PipelineArgs args) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRuleInitializer.cs:line 30

4908 07:18:53 ERROR UrlRewrite[web]::Exception occured when saving item after save - Item ID: {540C3ED4-E14C-4A34-9AFB-5F3C7251CBE0} Item Path: /sitecore/content/Sample Rewrites/Simple Internal Redirect
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: innerField
Source: Sitecore.Kernel
   at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
   at Sitecore.Data.Fields.CustomField..ctor(Field innerField)
   at Hi.UrlRewrite.Templates.Folders.RedirectFolderItem.get_SiteNameRestriction() in C:\git\UrlRewrite\Hi.UrlRewrite\Templates\Folders\RedirectFolderItem.cs:line 51
   at Hi.UrlRewrite.Processing.RulesEngine.GetSiteNameRestriction(RedirectFolderItem redirectFolder) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 221
   at Hi.UrlRewrite.Processing.RulesEngine.CreateInboundRuleFromSimpleRedirectItem(SimpleRedirectItem simpleRedirectItem, RedirectFolderItem redirectFolderItem) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 165
   at Hi.UrlRewrite.Processing.RulesEngine.GetInboundRules() in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 82
   at Hi.UrlRewrite.Processing.RulesEngine.UpdateRulesCache(Item item, Item redirectFolderItem, Action`3 action) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 309
   at Hi.UrlRewrite.Processing.RulesEngine.RefreshRule(Item item, Item redirectFolderItem) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 292
   at Hi.UrlRewrite.Processing.UrlRewriteItemEventHandler.RunItemSaved(Item item, ItemChanges itemChanges) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\UrlRewriteItemEventHandler.cs:line 82

**Comment by gaurav2ks** [comment]
We have found the resolution to this, this was not related to the module.

We had a validation enabled so that no two items in the content tree can have same name, due to this module was not installing they way it was expecting to installed.

We disabled the validation, installed the module and it worked fine.

Thanks
Gaurav

**Comment by iamandycohen** [comment]
Excellent.  Thanks for the update.
