### ISSUE TITLE
Method not found: 'Sitecore.Caching.ICache Sitecore.Caching.CustomCache.get_InnerCache()'

### ISSUE THREAD

**Issue by sagittarius-rbrisley** [iamandycohen/UrlRewrite#28]
Hi, First off thanks for the great module we have it on several installations and its been really great. I've just tried to install it on a Sitecore 8.0 (rev. 150812). I tried UrlRewrite 1.8 and 1.8.2 but just get this error in the log file.

6200 13:41:09 ERROR UrlRewrite::Exception during initialization.
Exception: System.MissingMethodException
Message: Method not found: 'Sitecore.Caching.ICache Sitecore.Caching.CustomCache.get_InnerCache()'.
Source: Hi.UrlRewrite
at Hi.UrlRewrite.Caching.RulesCache.SetRules[T](IEnumerable`1 outboundRules, String key)
at Hi.UrlRewrite.Caching.RulesCache.SetInboundRules(IEnumerable`1 inboundRules) in C:\git\UrlRewrite\Hi.UrlRewrite\Caching\RulesCache.cs:line 31
at Hi.UrlRewrite.Processing.RulesEngine.GetCachedInboundRules() in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 257
at Hi.UrlRewrite.Processing.InboundRuleInitializer.Process(PipelineArgs args) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRuleInitializer.cs:line 30

Any ideas why it might be happening before we try debugging it ourselves?

Best Regards
Richard

**Comment by iamandycohen** [comment]
Which version of sitecore are you on?

**Comment by sagittarius-rbrisley** [comment]
Sitecore 8.0 (rev. 150812) which is Update-5

**Comment by iamandycohen** [comment]
I haven't specifically made it compatible with update 5.  I will have this
done for you by Monday.

**Comment by sagittarius-rbrisley** [comment]
That's much appreciated many thanks!

**Comment by iamandycohen** [comment]
@sagittarius-rbrisley  I do not have that problem.  Are you sure you are installing the correct version of the module?  The caching error that you are referencing would only happen if you were installing the 8.2 versions.

Here is the file that you should be referencing.

https://github.com/iamandycohen/UrlRewrite/releases/download/v1.8/URL.Rewrite-1.8.zip
