### ISSUE TITLE
HttpException Server cannot append header after HTTP headers have been sent

### ISSUE THREAD

**Issue by CSharpDude** [iamandycohen/UrlRewrite#33]
Hi -

We are using the URL rewrite module to handle redirects from multiple old sites that now point to the new Sitecore site. The one issue we see is the logs have a lot of "_HttpException Server cannot append header after HTTP headers have been sen_t" errors. Has this been seen before or do we have something misconfigured perhaps?

Thanks,

Dave

**Comment by iamandycohen** [comment]
What version are you using?

**Comment by CSharpDude** [comment]
We are using 1.8.1.3.

Sample from the Sitecore log:
3472 18:43:51 INFO  UrlRewrite[web]::Redirecting http://www.academyofarthroscopy.com/gastroenterology-pulmonology/guide-wires.aspx to http://www.conmed.com/ [301]
3472 18:43:51 ERROR Application error.
Exception: System.Web.HttpException
Message: Server cannot append header after HTTP headers have been sent.
Source: System.Web
   at System.Web.HttpHeaderCollection.SetHeader(String name, String value, Boolean replace)
   at Sitecore.Web.XFrameOptionsHeaderModule.EndRequestHandler(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Thanks,

Dave
