### ISSUE TITLE
Sitecore 9 Support

### ISSUE THREAD

**Issue by gjaray-geekhive** [iamandycohen/UrlRewrite#43]
When Url Rewrite is installed in a sitecore 9 system I get the following error:
```Message: Method not found: 'Void Sitecore.Caching.CustomCache.SetObject(System.String, System.Object, Int64)'.
Source: Hi.UrlRewrite
   at Hi.UrlRewrite.Caching.RulesCache.SetRules[T](IEnumerable`1 outboundRules, String key)
   at Hi.UrlRewrite.Caching.RulesCache.SetInboundRules(IEnumerable`1 inboundRules) in C:\git\UrlRewrite\Hi.UrlRewrite\Caching\RulesCache.cs:line 31
   at Hi.UrlRewrite.Processing.RulesEngine.GetCachedInboundRules() in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RulesEngine.cs:line 254
   at Hi.UrlRewrite.Processing.InboundRuleInitializer.Process(PipelineArgs args) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRuleInitializer.cs:line 30
```
This appears to be similar to https://github.com/iamandycohen/UrlRewrite/issues/28 and leads me to believe that sitecore regularly changes their caching model.

Do you have any plans to support Sitecore 9 with this module?

**Comment by markgibbons25** [comment]
See https://github.com/davvves/UrlRewrite/tree/sc9update and I think you had an old version anyway
