### ISSUE TITLE
Error when redirecting

### ISSUE THREAD

**Issue by SitecoreBill** [iamandycohen/UrlRewrite#52]
I'm seeing this error in UrlRewrite log.  Please help, site needs to go live in 10 days.
Thanks in advance,
Bill

7332 15:15:04 ERROR UrlRewrite[web]::Exception occured
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Hi.UrlRewrite
   at Hi.UrlRewrite.Processing.RewriteHelper.ReplaceBackReferences(Match match, String input, String backReferenceVariable) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RewriteHelper.cs:line 30
   at Hi.UrlRewrite.Processing.RewriteHelper.ReplaceConditionBackReferences(Match conditionMatch, String input) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\RewriteHelper.cs:line 19
   at Hi.UrlRewrite.Processing.InboundRewriter.ProcessRedirectAction(InboundRule inboundRule, Uri uri, Match inboundRuleMatch, Match lastConditionMatch, InboundRuleResult ruleResult) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriter.cs:line 420
   at Hi.UrlRewrite.Processing.InboundRewriter.ProcessRegularExpressionInboundRule(Uri originalUri, InboundRule inboundRule) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriter.cs:line 273
   at Hi.UrlRewrite.Processing.InboundRewriter.ProcessInboundRule(Uri originalUri, InboundRule inboundRule) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriter.cs:line 207
   at Hi.UrlRewrite.Processing.InboundRewriter.ProcessRequestUrl(Uri requestUri, List`1 inboundRules) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriter.cs:line 59
   at Hi.UrlRewrite.Processing.InboundRewriteProcessor.ProcessUri(Uri requestUri, Database db, InboundRewriter urlRewriter) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriteProcessor.cs:line 76
   at Hi.UrlRewrite.Processing.InboundRewriteProcessor.Process(HttpRequestArgs args) in C:\git\UrlRewrite\Hi.UrlRewrite\Processing\InboundRewriteProcessor.cs:line 36

**Comment by iamandycohen** [comment]
Email me at andy.cohen@sitecore.com and I can help you out tomorrow.

**Comment by SitecoreBill** [comment]
Thanks Andy, will do.

**Comment by SitecoreBill** [comment]
Sorry, got busy with a deployment.  It was just files missing on CD servers.  Configs and a folder in layouts.  Actually there was one config that had to do with master db that caused a weird error that someone just happened to address, I just had to disable that one.  Maybe I missed a step in instructions?  All is good now thank you.
